version: '3'

services: 
    rating-service:
        build: ./RatingService/
        restart: always
        depends_on: 
            - mongodb
            
    communication-service:
        build: ./CommunicationService/
        ports:
            - 5002:5002
        restart: always
    
    ride-sharing-service:
        build: ./RideSharingService/
        restart: always
        depends_on: 
            - communication-service

    
        
    nginx:
        build: ./nginx/
        ports:
           - 7001:80
        depends_on:
           - ride-sharing-service
           - rating-service
        
    mongodb:
        image: mongo
        ports:
           - 27019:27017
        volumes:
            - db:/data/db
      
    
volumes:
     db:
    
    